# Generated by Django 4.0 on 2022-02-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='enrolled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='monthly_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('one', 'One Time'), ('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'Novemeber'), ('dec', 'December')], default='one', max_length=3)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.child')),
            ],
        ),
    ]
