# Generated by Django 4.0 on 2022-02-08 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_child_created_at_child_updated_at_fees_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
